//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace FruitToLime {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class GoImport {
        
        /// <remarks/>
        public Settings Settings;
        
        /// <remarks/>
        public Coworker[] Coworkers;
        
        /// <remarks/>
        public Organization[] Organizations;
        
        /// <remarks/>
        public Deal[] Deals;
        
        /// <remarks/>
        public Note[] Notes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Version Version;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Settings {
        
        /// <remarks/>
        public ClassSettings Organization;
        
        /// <remarks/>
        public ClassSettings Person;
        
        /// <remarks/>
        public ClassSettings Deal;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClassSettings {
        
        /// <remarks/>
        public CustomField[] CustomFields;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomField {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DealReference {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public string Heading;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Note {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public System.DateTime Date;
        
        /// <remarks/>
        public string Text;
        
        /// <remarks/>
        public string Classification;
        
        /// <remarks/>
        public System.DateTime DateCreated;
        
        /// <remarks/>
        public CoworkerReference CreatedBy;
        
        /// <remarks/>
        public OrganizationReference Organization;
        
        /// <remarks/>
        public DealReference Deal;
        
        /// <remarks/>
        public PersonReference Person;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoworkerReference {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public string Heading;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrganizationReference {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public string Heading;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonReference {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public string Heading;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Status {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Label;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Deal {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OfferDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OrderDate;
        
        /// <remarks/>
        public OrganizationReference Customer;
        
        /// <remarks/>
        public Status Status;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public int Probability;
        
        /// <remarks/>
        public long Value;
        
        /// <remarks/>
        public PersonReference CustomerContact;
        
        /// <remarks/>
        public CoworkerReference ResponsibleCoworker;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag")]
        public string[] Tags;
        
        /// <remarks/>
        public CustomValue[] CustomValues;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomValue {
        
        /// <remarks/>
        public CustomFieldReference Field;
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomFieldReference {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Person {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public ReferenceToSource Source;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public string DirectPhoneNumber;
        
        /// <remarks/>
        public string FaxPhoneNumber;
        
        /// <remarks/>
        public string MobilePhoneNumber;
        
        /// <remarks/>
        public string HomePhoneNumber;
        
        /// <remarks/>
        public string Position;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag")]
        public string[] Tags;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public string AlternativeEmail;
        
        /// <remarks/>
        public Address PostalAddress;
        
        /// <remarks/>
        public bool CurrentlyEmployed;
        
        /// <remarks/>
        public CustomValue[] CustomValues;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReferenceToSource {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public ReferenceFormat Format;
        
        /// <remarks/>
        public string Id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum ReferenceFormat {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Address {
        
        /// <remarks/>
        public string Street;
        
        /// <remarks/>
        public string ZipCode;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public string CountryCode;
        
        /// <remarks/>
        public string Location;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Organization {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public ReferenceToSource Source;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string OrganizationNumber;
        
        /// <remarks/>
        public Address PostalAddress;
        
        /// <remarks/>
        public Address VisitAddress;
        
        /// <remarks/>
        public string CentralPhoneNumber;
        
        /// <remarks/>
        public string FaxPhoneNumber;
        
        /// <remarks/>
        public string MobilePhoneNumber;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public string WebSite;
        
        /// <remarks/>
        public Person[] Employees;
        
        /// <remarks/>
        public CustomValue[] CustomValues;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag")]
        public string[] Tags;
        
        /// <remarks/>
        public CoworkerReference ResponsibleCoworker;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Coworker {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string IntegrationId;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string LastName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum Version {
        
        /// <remarks/>
        v1_0,
        
        /// <remarks/>
        v2_0,
    }
}
