//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace FruitToLime {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class GoImport {
        
        private Settings settingsField;
        
        private Coworker[] coworkersField;
        
        private Organization[] organizationsField;
        
        private Deal[] dealsField;
        
        private Note[] notesField;
        
        private Version versionField;
        
        /// <remarks/>
        public Settings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        public Coworker[] Coworkers {
            get {
                return this.coworkersField;
            }
            set {
                this.coworkersField = value;
            }
        }
        
        /// <remarks/>
        public Organization[] Organizations {
            get {
                return this.organizationsField;
            }
            set {
                this.organizationsField = value;
            }
        }
        
        /// <remarks/>
        public Deal[] Deals {
            get {
                return this.dealsField;
            }
            set {
                this.dealsField = value;
            }
        }
        
        /// <remarks/>
        public Note[] Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Version Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Settings {
        
        private ClassSettings organizationField;
        
        private ClassSettings personField;
        
        private ClassSettings dealField;
        
        /// <remarks/>
        public ClassSettings Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public ClassSettings Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public ClassSettings Deal {
            get {
                return this.dealField;
            }
            set {
                this.dealField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClassSettings {
        
        private CustomField[] customFieldsField;
        
        /// <remarks/>
        public CustomField[] CustomFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomField {
        
        private string idField;
        
        private string integrationIdField;
        
        private string titleField;
        
        private string typeField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DealReference {
        
        private string idField;
        
        private string integrationIdField;
        
        private string headingField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Note {
        
        private string idField;
        
        private string integrationIdField;
        
        private System.DateTime dateField;
        
        private string textField;
        
        private string classificationField;
        
        private System.DateTime dateCreatedField;
        
        private CoworkerReference createdByField;
        
        private OrganizationReference organizationField;
        
        private DealReference dealField;
        
        private PersonReference personField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public CoworkerReference CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public OrganizationReference Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public DealReference Deal {
            get {
                return this.dealField;
            }
            set {
                this.dealField = value;
            }
        }
        
        /// <remarks/>
        public PersonReference Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoworkerReference {
        
        private string idField;
        
        private string integrationIdField;
        
        private string headingField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrganizationReference {
        
        private string idField;
        
        private string integrationIdField;
        
        private string headingField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonReference {
        
        private string idField;
        
        private string integrationIdField;
        
        private string headingField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Status {
        
        private string idField;
        
        private string labelField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Deal {
        
        private string idField;
        
        private string integrationIdField;
        
        private string nameField;
        
        private System.Nullable<System.DateTime> offerDateField;
        
        private System.Nullable<System.DateTime> orderDateField;
        
        private OrganizationReference customerField;
        
        private Status statusField;
        
        private string descriptionField;
        
        private int probabilityField;
        
        private long valueField;
        
        private PersonReference customerContactField;
        
        private CoworkerReference responsibleCoworkerField;
        
        private string[] tagsField;
        
        private CustomValue[] customValuesField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OfferDate {
            get {
                return this.offerDateField;
            }
            set {
                this.offerDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public OrganizationReference Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Probability {
            get {
                return this.probabilityField;
            }
            set {
                this.probabilityField = value;
            }
        }
        
        /// <remarks/>
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public PersonReference CustomerContact {
            get {
                return this.customerContactField;
            }
            set {
                this.customerContactField = value;
            }
        }
        
        /// <remarks/>
        public CoworkerReference ResponsibleCoworker {
            get {
                return this.responsibleCoworkerField;
            }
            set {
                this.responsibleCoworkerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag")]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public CustomValue[] CustomValues {
            get {
                return this.customValuesField;
            }
            set {
                this.customValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomValue {
        
        private CustomFieldReference fieldField;
        
        private string valueField;
        
        /// <remarks/>
        public CustomFieldReference Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomFieldReference {
        
        private string idField;
        
        private string integrationIdField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Person {
        
        private string idField;
        
        private string integrationIdField;
        
        private ReferenceToSource sourceField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string directPhoneNumberField;
        
        private string faxPhoneNumberField;
        
        private string mobilePhoneNumberField;
        
        private string homePhoneNumberField;
        
        private string positionField;
        
        private string[] tagsField;
        
        private string emailField;
        
        private string alternativeEmailField;
        
        private Address postalAddressField;
        
        private bool currentlyEmployedField;
        
        private CustomValue[] customValuesField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceToSource Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string DirectPhoneNumber {
            get {
                return this.directPhoneNumberField;
            }
            set {
                this.directPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FaxPhoneNumber {
            get {
                return this.faxPhoneNumberField;
            }
            set {
                this.faxPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNumber {
            get {
                return this.mobilePhoneNumberField;
            }
            set {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string HomePhoneNumber {
            get {
                return this.homePhoneNumberField;
            }
            set {
                this.homePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag")]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string AlternativeEmail {
            get {
                return this.alternativeEmailField;
            }
            set {
                this.alternativeEmailField = value;
            }
        }
        
        /// <remarks/>
        public Address PostalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool CurrentlyEmployed {
            get {
                return this.currentlyEmployedField;
            }
            set {
                this.currentlyEmployedField = value;
            }
        }
        
        /// <remarks/>
        public CustomValue[] CustomValues {
            get {
                return this.customValuesField;
            }
            set {
                this.customValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReferenceToSource {
        
        private string nameField;
        
        private ReferenceFormat formatField;
        
        private string idField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceFormat Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum ReferenceFormat {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Address {
        
        private string streetField;
        
        private string zipCodeField;
        
        private string cityField;
        
        private string countryCodeField;
        
        private string locationField;
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Organization {
        
        private string idField;
        
        private string integrationIdField;
        
        private ReferenceToSource sourceField;
        
        private string nameField;
        
        private string organizationNumberField;
        
        private Address postalAddressField;
        
        private Address visitAddressField;
        
        private string centralPhoneNumberField;
        
        private string faxPhoneNumberField;
        
        private string mobilePhoneNumberField;
        
        private string emailField;
        
        private string webSiteField;
        
        private Person[] employeesField;
        
        private CustomValue[] customValuesField;
        
        private string[] tagsField;
        
        private CoworkerReference responsibleCoworkerField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceToSource Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationNumber {
            get {
                return this.organizationNumberField;
            }
            set {
                this.organizationNumberField = value;
            }
        }
        
        /// <remarks/>
        public Address PostalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        public Address VisitAddress {
            get {
                return this.visitAddressField;
            }
            set {
                this.visitAddressField = value;
            }
        }
        
        /// <remarks/>
        public string CentralPhoneNumber {
            get {
                return this.centralPhoneNumberField;
            }
            set {
                this.centralPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FaxPhoneNumber {
            get {
                return this.faxPhoneNumberField;
            }
            set {
                this.faxPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNumber {
            get {
                return this.mobilePhoneNumberField;
            }
            set {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string WebSite {
            get {
                return this.webSiteField;
            }
            set {
                this.webSiteField = value;
            }
        }
        
        /// <remarks/>
        public Person[] Employees {
            get {
                return this.employeesField;
            }
            set {
                this.employeesField = value;
            }
        }
        
        /// <remarks/>
        public CustomValue[] CustomValues {
            get {
                return this.customValuesField;
            }
            set {
                this.customValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag")]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public CoworkerReference ResponsibleCoworker {
            get {
                return this.responsibleCoworkerField;
            }
            set {
                this.responsibleCoworkerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Coworker {
        
        private string idField;
        
        private string integrationIdField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum Version {
        
        /// <remarks/>
        v1_0,
        
        /// <remarks/>
        v2_0,
    }
}
