name: CD

on:
  push:
    branches: master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1 

    - name: Build gem
      run: gem build move-to-go.gemspec
    
    - name: Set up gem credentials
      run: |
        set +x
        mkdir -p ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
        EOF
        chmod 0600 ~/.gem/credentials
        set -x

    - name: Push gem
      run: gem push move-to-go-*.gem