name: Release

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install tooling
      uses: actions/checkout@v3
      run: bundle install
    - name: Tools unit tests
      run: bundle exec rake spec

