name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Install tooling
      run: bundle install

    - name: Tools unit tests
      run: bundle exec rake spec

